package com.example.svetlogorskchpp.__domain.en.electrical_equipment

enum class ElCategory(val str: String) {
    OTHER("Остальное"),
    TREATMENT_FACILITIES("Оч. сооружения"),
    DESALTING("Обессоливание"),
    BNT("БНТ"),
    Bagernaya("Багерная"),
    KO("К/О"),
    KTC_KO("КТЦ к/о"),
    KTC_TO("КТЦ т/о"),
    NDV("НДВ"),
    PN("ПН"),
    PEN("ПЭН"),
    PRETREATMENT("Предочистка"),
    SN("СН"),
    TY("ТУ"),
    CN("ЦН"),
    CCR("ЦЦР"),
    AMMONIA("Аммиачное х-во"),
    GIDROZIYNOE("Гидразийное х-во"),
    ACIDIC("Кислотное х-во"),
    COAGULANT("Коагулянтное х-во"),
    N_TS("Насосная 1 оч. т/с"),
    SOVEVOE("Солевое х-во"),
    LIMESTONE("Сх. известкового х-во"),
    PHOSPHATE("Сх. фосфатного х-во"),
    NVK("Узел НВК промывки"),
    ALKALINE("Щелочное х-во"),
    TG_1("ТГ-1"),
    TG_3("ТГ-3"),
    TG_4("ТГ-4"),
    TG_5("ТГ-5"),
    TG_6("ТГ-6"),
    KA_1("К/А-1"),
    KA_6("К/А-6"),
    KA_7("К/А-7"),
    KA_8("К/А-8"),
    KA_9("К/А-9"),
}