package com.example.svetlogorskchpp.model.inspectionSchedule

enum class InSc(val get: String) {
    NSE ("НСЭ"),
    DEM ("ДЭМ"),
    DAY ("день"),
    NIGHT ("ночь"),
    DAY_NIGHT("день/ночь"),
    WORKING_SHIFT ("workingShift"),
    EXECUTOR ("executor"),
    ALL ("all"),
    INSPECTION_SCHEDULE ("ГрафикОсмотра"),
    MONTH ("month"),
    DAY_OF_THE_WEEK ("dayOfTheWeek"),
    WEEK ("week"),
    DAY_MONTH ("dayMonth"),
    INTERVAL ("interval"),
    JANUARY ("january"),
    FEBRUARY ("february"),
    MARCH ("march"),
    APRIL ("april"),
    MAY ("may"),
    JUNE ("june"),
    JULY ("july"),
    AUGUST ("august"),
    SEPTEMBER ("september"),
    OCTOBER ("october"),
    NOVEMBER ("november"),
    DECEMBER ("december"),
    MONDAY ("monday"),
    TUESDAY ("tuesday"),
    WEDNESDAY ("wednesday"),
    THURSDAY ("thursday"),
    FRIDAY ("friday"),
    SATURDAY ("saturday"),
    SUNDAY ("sunday"),
    FIRST ("first"),
    SECOND ("second"),
    THIRD ("third"),
    LAST ("last"),
    CHECKLIST ("Перечни"),
    INSPECTION ("Осмотр"),
    VALVE ("Задвижки"),
    SCHEME ("Схема"),
    LOCATION ("Расположение"),
    CONTROL ("Управление"),
    DIRECTION ("Направление")

}